#!/system/xbin/busybox sh

	adr=`grep nr_running /proc/kallsyms | cut -f1 -d" "`
	insmod /system/lib/modules/cpufreq_interactive.ko nr_running_addr=0x$adr

	adr=`grep omap2_clk_init_cpufreq_table /proc/kallsyms | cut -f1 -d" "`
	insmod /system/lib/modules/overclock_milestone_21.ko omap2_clk_init_cpufreq_table_addr=0x$adr
	mount /dev/block/mmcblk0p1 /sdcard
	if [ -e /sdcard/oc-settings ] ; then
		cp /sdcard/oc-settings /data/execme
		chmod 755 /data/execme
		/data/execme
		# echo 46 > /proc/overclock/max_vsel
		# echo 800000 > /proc/overclock/max_rate
		# echo 1 125000000 12 > /proc/overclock/mpu_opps
		# echo 2 250000000 26 > /proc/overclock/mpu_opps
		# echo 3 400000000 30 > /proc/overclock/mpu_opps
		# echo 4 600000000 34 > /proc/overclock/mpu_opps
		# echo 5 800000000 46 > /proc/overclock/mpu_opps
		# echo 0 800000 > /proc/overclock/freq_table
		# echo 1 400000 > /proc/overclock/freq_table
		# echo 2 250000 > /proc/overclock/freq_table
		# echo 3 125000 > /proc/overclock/freq_table
	fi
	umount /sdcard

# enable sd-ext
	if [ -e /dev/block/mmcblk0p2 ] ; then
		insmod /system/lib/modules/ext2.ko
		insmod /system/lib/modules/jbd.ko
		insmod /system/lib/modules/ext3.ko
		mount /dev/block/mmcblk0p2 /sd-ext
		if [ $? -eq 0 ] ; then
			mkdir /sd-ext/app ; chmod 777 /sd-ext/app
			[[ -d /data/app ]] && cp -a /data/app/* /sd-ext/app/
			[[ -d /data/app ]] && rm -R /data/app
			ln -s /sd-ext/app /data/app
		fi
	fi
