#!/system/xbin/busybox sh

## Load Milestone Overclock module
adr=`grep omap2_clk_init_cpufreq_table /proc/kallsyms | cut -f1 -d" "`
insmod /system/lib/modules/overclock_milestone_21.ko omap2_clk_init_cpufreq_table_addr=0x$adr

## Exit if module not loaded
[ -d /proc/overclock ] || exit

## Load oc-settings from sdcard
# Beware! There is no way to test the oc-settings are safe for this
# device... Maybe it should be to oc-settings-xt720 or put in a
# device-specific folder on the sdcard...
mount -oro /dev/block/mmcblk0p1 /sdcard
if [ -e /sdcard/oc-settings ] ; then
    echo found oc-settings
    dos2unix /sdcard/oc-settings > /data/oc-settings
    chmod 755 /data/oc-settings
    /data/oc-settings
    # echo 46 > /proc/overclock/max_vsel
    # echo 800000 > /proc/overclock/max_rate
    # echo 1 125000000 12 > /proc/overclock/mpu_opps
    # echo 2 250000000 26 > /proc/overclock/mpu_opps
    # echo 3 400000000 30 > /proc/overclock/mpu_opps
    # echo 4 600000000 34 > /proc/overclock/mpu_opps
    # echo 5 800000000 46 > /proc/overclock/mpu_opps
    # echo 0 800000 > /proc/overclock/freq_table
    # echo 1 400000 > /proc/overclock/freq_table
    # echo 2 250000 > /proc/overclock/freq_table
    # echo 3 125000 > /proc/overclock/freq_table
fi

## Autoload Milestone Overclock settings
# Milestone Overclock saves it's autoload values inside:
pathprefs=/data/data/pt.com.darksun.milestoneoverclock/shared_prefs/MilestoneOverclockPrefs.xml
# Milestone Overclocks saves the autoload preference by creating or
# destroying this file on the sdcard:
pathautoload=/sdcard/Android/data/pt.com.darksun.milestoneoverclock/files/autoload

getMilestoneOverclockPref () {
    tr -dc '[[:alnum:]>"]' < $pathprefs \
	| tr \> \\n \
	| egrep "^longname\"$1\"value\"[0-9]+\"$" \
	| cut -f 4 -d \"
}

## Make sure module is loaded and that autoload is requested
# Beware! It's possible the user had autoload set/saved on the sdcard
# from a previous ROM but has no preferences! So check for both.
if [ -f $pathautoload -a -f $pathprefs ] ; then
    # Extract max_rate, max_vsel values from Milestone Overclock
    # preferences
    autoloadRate=$(getMilestoneOverclockPref autoloadRate)
    autoloadVsel=$(getMilestoneOverclockPref autoloadVsel)

    # Ensure both values were successfully read
    if [ ! -z "$autoloadRate" -a ! -z "$autoloadVsel" ] ; then
	echo $autoloadRate > /proc/overclock/max_rate
	echo $autoloadVsel > /proc/overclock/max_vsel
    fi
fi

umount /sdcard
